Repository dusk-network/itn-installer, pull requests merged in 2022-12, with the labels that each got.

#6 Update rusk wallet and add extra output
  itn-installer.sh
Labels: mark:testnet, type:enhancement

#9 Added documentation to the README
  README.md
Labels: area:documentation, mark:testnet, type:docs

#11 Add logrotate
  itn-installer.sh
  services/logrotate.conf
Labels: mark:testnet

#15 Fix logrotate
  itn-installer.sh
  services/logrotate.conf
Labels: mark:testnet

#16 Consensus pwd setup
  README.md
  bin/setup_consensus_pwd.sh
  itn-installer.sh
Labels: mark:testnet

#17 Release 0.0.4
  README.md
Labels: mark:testnet
